name = "dimas-os"
compatibility_date = "2024-03-20"
pages_build_output_dir = ".vercel/output/static"


[[d1_databases]]
binding = "DB"
database_name = "dimas_os_db"
database_id = "c61b2db7-5339-47a3-8987-40a99b1b6cfb"
